// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationSystemASP.Models;

namespace ReservationSystemASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReservationSystemASP.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountPlaces")
                        .HasColumnType("int");

                    b.Property<int?>("SeanseId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeanseId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ReservationSystemASP.Models.SeanseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountPlaces")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("SeanseEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("SeanseStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Seanses");
                });

            modelBuilder.Entity("ReservationSystemASP.Models.BookModel", b =>
                {
                    b.HasOne("ReservationSystemASP.Models.SeanseModel", "Seanse")
                        .WithMany("Bookings")
                        .HasForeignKey("SeanseId");

                    b.Navigation("Seanse");
                });

            modelBuilder.Entity("ReservationSystemASP.Models.SeanseModel", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
